-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["PlayerPlane_isolated"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 3, friction = 0.8, bounce = 0.01, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -60, -7.5  ,  -70, 9.5  ,  -88, -21.5  ,  -88, -23.5  ,  -82, -26.5  ,  -67, -25.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0.8, bounce = 0.01, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   93, 11.5  ,  82, 13.5  ,  82, -4.5  ,  91, -3.5  ,  99, -0.5  ,  100, 6.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0.8, bounce = 0.01, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -25, 17.5  ,  82, -4.5  ,  1, 22.5  ,  -20, 21.5  ,  -25, 20.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0.8, bounce = 0.01, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   76, 23.5  ,  41, 23.5  ,  82, -4.5  ,  82, 13.5  ,  80, 22.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0.8, bounce = 0.01, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -94, -11.5  ,  -70, 9.5  ,  -83, 10.5  ,  -95, 8.5  ,  -98, 6.5  ,  -100, 0.5  ,  -100, -4.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0.8, bounce = 0.01, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   41, -11.5  ,  45, -4.5  ,  -9, -13.5  ,  -5, -16.5  ,  35, -16.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0.8, bounce = 0.01, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -90, -20.5  ,  -88, -21.5  ,  -70, 9.5  ,  -94, -11.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0.8, bounce = 0.01, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -67, 10.5  ,  -15, -12.5  ,  -9, -13.5  ,  45, -4.5  ,  -47, 13.5  ,  -67, 12.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0.8, bounce = 0.01, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   20, 25.5  ,  1, 22.5  ,  82, -4.5  ,  41, 23.5  ,  36, 25.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0.8, bounce = 0.01, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -47, 13.5  ,  45, -4.5  ,  82, -6.5  ,  82, -4.5  ,  -25, 17.5  ,  -32, 17.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0.8, bounce = 0.01, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -15, -12.5  ,  -67, 10.5  ,  -70, 9.5  ,  -50, -7.5  ,  -31, -11.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0.8, bounce = 0.01, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -50, -7.5  ,  -70, 9.5  ,  -60, -7.5  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

